<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PagSeguro\Controller\PagSeguroController' => __DIR__ . '/src/PagSeguro/Controller/PagSeguroController.php',
    'PagSeguro\Factory\ModuleOptionsFactory' => __DIR__ . '/src/PagSeguro/Factory/ModuleOptionsFactory.php',
    'PagSeguro\Factory\PagSeguroControllerFactory' => __DIR__ . '/src/PagSeguro/Factory/PagSeguroControllerFactory.php',
    'PagSeguro\Factory\PagSeguroRequestFactory' => __DIR__ . '/src/PagSeguro/Factory/PagSeguroRequestFactory.php',
    'PagSeguro\Model\Checkout' => __DIR__ . '/src/PagSeguro/Model/Checkout.php',
    'PagSeguro\Model\Item' => __DIR__ . '/src/PagSeguro/Model/Item.php',
    'PagSeguro\Model\Sender' => __DIR__ . '/src/PagSeguro/Model/Sender.php',
    'PagSeguro\Model\Shipping' => __DIR__ . '/src/PagSeguro/Model/Shipping.php',
    'PagSeguro\Model\Transaction' => __DIR__ . '/src/PagSeguro/Model/Transaction.php',
    'PagSeguro\Module' => __DIR__ . '/src/PagSeguro/Module.php',
    'PagSeguro\Options\ModuleOptions' => __DIR__ . '/src/PagSeguro/Options/ModuleOptions.php',
    'PagSeguro\Service\PagSeguroProcessTransactionInterface' => __DIR__ . '/src/PagSeguro/Service/PagSeguroProcessTransactionInterface.php',
    'PagSeguro\Service\PagSeguroRequest' => __DIR__ . '/src/PagSeguro/Service/PagSeguroRequest.php',
    'PagSeguro\Service\TransactionRequest' => __DIR__ . '/src/PagSeguro/Service/TransactionRequest.php',
    'PagSegurotest\Bootstrap' => __DIR__ . '/test/Bootstrap.php',
    'PagSeguroTest\IntegratedTest' => __DIR__ . '/test/PagSeguroTest/IntegratedTest.php',
    'PagSeguroTest\Model\CheckoutTest' => __DIR__ . '/test/PagSeguroTest/Model/CheckoutTest.php',
    'PagSeguroTest\Model\ItemTest' => __DIR__ . '/test/PagSeguroTest/Model/ItemTest.php',
    'PagSeguroTest\Model\SenderTest' => __DIR__ . '/test/PagSeguroTest/Model/SenderTest.php'
);
