<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PagSeguro\Factory\ModuleOptionsFactory' => __DIR__ . '/src/PagSeguro/Factory/ModuleOptionsFactory.php',
    'PagSeguro\Factory\PagSeguroRequestFactory' => __DIR__ . '/src/PagSeguro/Factory/PagSeguroRequestFactory.php',
    'PagSeguro\Model\Checkout' => __DIR__ . '/src/PagSeguro/Model/Checkout.php',
    'PagSeguro\Model\Item' => __DIR__ . '/src/PagSeguro/Model/Item.php',
    'PagSeguro\Model\Sender' => __DIR__ . '/src/PagSeguro/Model/Sender.php',
    'PagSeguro\Model\Shipping' => __DIR__ . '/src/PagSeguro/Model/Shipping.php',
    'PagSeguro\Module' => __DIR__ . '/src/PagSeguro/Module.php',
    'PagSeguro\Options\ModuleOptions' => __DIR__ . '/src/PagSeguro/Options/ModuleOptions.php',
    'PagSeguro\Service\PagSeguroRequest' => __DIR__ . '/src/PagSeguro/Service/PagSeguroRequest.php'
);
